<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Product>DIYB</Product>
    <Authors>gillesg77</Authors>
    <Company>gillesg77</Company>
    <Copyright>Copyright (c) 2026 gillesg77</Copyright>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
